version: "3"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn backend.wsqi.application --bind 0.0.0.0:8000

        volumes:
            - .:/code
        ports:
            - "8000:8000"
