version: "3.8"

services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "8000:80"
        volumes:
            - ./django/venti/nginx:/etc/nginx.conf.d
            - ./django/app:/app
            - ./django/venti/static:/static
        depends_on:
            - django_app

    django_app:
        container_name: django_app
        build:
            context: .
            dockerfile: ./django/Dockerfile
        command: gunicorn daliyInGsm.wsgi:application --bind 0.0.0.0:8000
        expose:
            - "8000"
        depends_on:
            - mysql
        links:
            - mysql:mysql
        restart: always
        volumes:
            - ./django/app:/app
        env_file:
            - ./django/env.dev

networks:
    app-tier:
        driver: bridge
