version: "3"
services:
    django:
        build:
            context: .
            dockerfile: Dockerfile.production
        image: 838235863925.dkr.ecr.ap-northeast-2.amazonaws.com/dig
        container_name: django-container
        entrypoint:
            - daliyInGsm/nginx/docker-entrypoint.production.sh
    nginx:
        build:
            context: ./nginx
            dockerfile: ./Dockerfile.production
        image: 838235863925.dkr.ecr.ap-northeast-2.amazonaws.com/dig-nginx
        container_name: nginx-container
        ports:
            - "80"
        depends_on:
            - django
        entrypoint:
            - ./docker-entrypoint.production.sh
