# Generated by Django 4.1.3 on 2022-11-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='NICKNAME')),
                ('profile_image', models.URLField(max_length=255, verbose_name='PROFILE_IMAGE')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='EMAIL')),
                ('bio', models.TextField(verbose_name='BIO')),
            ],
        ),
    ]
