apiVersion: v1
kind: Service
    metadata:
      name: django-app
      namespace: prd-api
    annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
          targetPort: 8000
          protocol: TCP
        - name: https
          port: 443
          targetPort: 8000
          protocol: TCP
    selector:
        service: app
